### ISSUE TITLE
Fix case sensitivity for GeoJSON files

### ISSUE THREAD

**Issue by atima** [go-cart-io/cartogram-web#9]
**Issue:** JSON files for all maps are not found.

![image](https://github.com/user-attachments/assets/1edd1e6a-aae5-4fd1-a54c-814d2d5b066c)

**Cause:** GeoJSON files are stored in lowercase (e.g., `population.json`), but the frontend requests them in uppercase (e.g., `Population.json`).

**Solution:**
In the `cartdata `folder, rename all `original.json` files to `Original.json` and `population.json` files to `Population.json`.
Review the codebase to ensure consistency, as `original.json` might be used in some places.

**Comment by atima** [comment]
I fixed it in development branch (0334ec3a024a9f37161e32b97823482acf65b635). @adisidev if the issue is solved, please close the issue.

**Comment by adisidev** [comment]
Something is somehow still not working, but I am unsure whether it is still because of this, or something else. If you are free some time, I would really appreciate learning some web debugging techniques from you.
